-- EventOS: MER oficial de cinco entidades com Inscrição central.
-- Categoria é catálogo global, com preço vigente comum a todas as edições.
-- Executar integralmente numa base limpa.

START TRANSACTION;

CREATE TABLE evento (
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(200) NOT NULL,
    sigla VARCHAR(30),
    CONSTRAINT pk_evento PRIMARY KEY (id_evento),
    CONSTRAINT ck_evento_id CHECK (id_evento > 0),
    CONSTRAINT ck_evento_nome CHECK (CHAR_LENGTH(TRIM(nome)) > 0),
    CONSTRAINT ck_evento_sigla CHECK (sigla IS NULL OR CHAR_LENGTH(TRIM(sigla)) > 0)
);

CREATE TABLE edicao (
    id_edicao BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_evento BIGINT NOT NULL,
    designacao VARCHAR(60) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    modalidade VARCHAR(10) NOT NULL,
    local_realizacao VARCHAR(200),
    abertura_inscricoes DATE NOT NULL,
    fechamento_inscricoes DATE NOT NULL,
    CONSTRAINT pk_edicao PRIMARY KEY (id_edicao),
    CONSTRAINT ck_edicao_id CHECK (id_edicao > 0),
    CONSTRAINT fk_edicao_evento FOREIGN KEY (id_evento) REFERENCES evento (id_evento),
    CONSTRAINT ck_edicao_designacao CHECK (CHAR_LENGTH(TRIM(designacao)) > 0),
    CONSTRAINT ck_edicao_realizacao CHECK (data_inicio <= data_fim),
    CONSTRAINT ck_edicao_janela CHECK (abertura_inscricoes <= fechamento_inscricoes AND fechamento_inscricoes <= data_fim),
    CONSTRAINT ck_edicao_modalidade CHECK (modalidade IN ('PRESENCIAL', 'HIBRIDA', 'REMOTA')),
    CONSTRAINT ck_edicao_local CHECK (modalidade NOT IN ('PRESENCIAL', 'HIBRIDA', 'REMOTA') OR (modalidade = 'REMOTA' AND local_realizacao IS NULL) OR (modalidade IN ('PRESENCIAL', 'HIBRIDA') AND local_realizacao IS NOT NULL AND CHAR_LENGTH(TRIM(local_realizacao)) > 0))
);

CREATE TABLE participante (
    id_participante BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_completo VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    cpf VARCHAR(11),
    CONSTRAINT pk_participante PRIMARY KEY (id_participante),
    CONSTRAINT ck_participante_id CHECK (id_participante > 0),
    CONSTRAINT uq_participante_cpf UNIQUE (cpf),
    CONSTRAINT ck_participante_nome CHECK (CHAR_LENGTH(TRIM(nome_completo)) > 0),
    CONSTRAINT ck_participante_email CHECK (CHAR_LENGTH(TRIM(email)) > 0),
    CONSTRAINT ck_participante_cpf CHECK (cpf IS NULL OR cpf SIMILAR TO '[0-9]{11}')
);

CREATE TABLE categoria (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(80) NOT NULL,
    descricao VARCHAR(300),
    preco_vigente DECIMAL(12,2) NOT NULL,
    CONSTRAINT pk_categoria PRIMARY KEY (id_categoria),
    CONSTRAINT ck_categoria_id CHECK (id_categoria > 0),
    CONSTRAINT uq_categoria_nome UNIQUE (nome),
    CONSTRAINT ck_categoria_nome CHECK (CHAR_LENGTH(TRIM(nome)) > 0),
    CONSTRAINT ck_categoria_descricao CHECK (descricao IS NULL OR CHAR_LENGTH(TRIM(descricao)) > 0),
    CONSTRAINT ck_categoria_preco CHECK (preco_vigente > 0)
);

CREATE TABLE inscricao (
    id_inscricao BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_participante BIGINT NOT NULL,
    id_categoria BIGINT NOT NULL,
    id_edicao BIGINT NOT NULL,
    data_inscricao DATE NOT NULL,
    situacao VARCHAR(9) DEFAULT 'PENDENTE' NOT NULL,
    valor_contratado DECIMAL(12,2) NOT NULL,
    canal_divulgacao VARCHAR(11),
    CONSTRAINT pk_inscricao PRIMARY KEY (id_inscricao),
    CONSTRAINT ck_inscricao_id CHECK (id_inscricao > 0),
    CONSTRAINT fk_inscricao_participante FOREIGN KEY (id_participante) REFERENCES participante (id_participante),
    CONSTRAINT fk_inscricao_categoria FOREIGN KEY (id_categoria) REFERENCES categoria (id_categoria),
    CONSTRAINT fk_inscricao_edicao FOREIGN KEY (id_edicao) REFERENCES edicao (id_edicao),
    CONSTRAINT uq_inscricao_participante_edicao UNIQUE (id_participante, id_edicao),
    CONSTRAINT ck_inscricao_situacao CHECK (situacao IN ('PENDENTE', 'PAGA', 'CANCELADA')),
    CONSTRAINT ck_inscricao_valor CHECK (valor_contratado > 0),
    CONSTRAINT ck_inscricao_canal CHECK (canal_divulgacao IS NULL OR canal_divulgacao IN ('SITE_EVENTO', 'REDE_SOCIAL', 'EMAIL', 'INDICACAO', 'OUTRO'))
);

COMMIT;
